### ISSUE TITLE
Architectural changes: Tokio + Modules

### ISSUE THREAD

**Issue by horenso** [ElektraInitiative/opensesame#74]
This issue is to keep track of the architectual changes in main and the restructure of the system into "modules", which work independenly of each other.

@fel115 and myself identified the following functunality (work in progress, I'm just dumping them here)

- [ ] Config (libelektra)
- [ ] Nextcloud (bidirectonal status and commands, reusing http client/connections)
- [ ] Weather Station
- [ ] Sensor (has fire alarm)
- [ ] Buttons (MOD-IO2)
- [ ] Validator
- [ ] Garage / Door / Light
- [ ] Bat (battery supply and warning about battery mode)
- [ ] Watchdog
- [ ] PWR
- [ ] Environment (MOD-ENV)
- [ ] SSH / Other way of distributed communication

At the moment, there are two independet loops in main, "sensor mode" and "normal mode". To reason about the current architecture more clearly we refactored it (https://github.com/horenso/opensesame/blob/refactor_main/src/main.rs) into diffenent methods, without changing the semantics. This is helpful to see what parts are actually used in which loop.

The next step is to identify all blocking calls and research alternatives. For sure, all file operations (like `lines()`) must be replaced with async methods (like `tokio::fs`).

Modules can be enabled/disabled. Some things above (like config) are global whereas Nextcloud, Button and Sensors should become modules. More details about the exact interfaces follow.

**Comment by markus2330** [comment]
Thank you for creating this issue!

> following functunality

I added `-  [ ]` so that you can track progress by clicking on the items. I also prioritized them, in which order I would like to test (weather station + sensors first).

> (MOD-IO2, has fire alarm)

What do you mean with that? Sensor does not need MOD-IO2.

> This is helpful to see what parts are actually used in which loop.

I am not sure if we are on the same page: these two loops are arbitrary and don't have any relevance. Any module should work together with any other module, there shouldn't be a normal or sensor mode. Sensors should be a normal module like any other.

> The next step is to identify all blocking calls and research alternatives. 

First the interfaces.

It is important that we have intermediate steps every day, so that we soon can start testing. Let us first get weather station+sensors running on the new architecture (the file writes done in the sensor loop can be dropped, they are not important).

> Modules can be enabled/disabled.

:+1: 

> Some things above (like config) are global whereas Nextcloud, Button and Sensors should become modules.

Nextcloud in general also needs to be global. Ping could be a module.

> More details about the exact interfaces follow.

Looking forward to :rocket:

**Comment by horenso** [comment]
Thanks for the comments!

> What do you mean with that? Sensor does not need MOD-IO2.

What is the MOD-IO2 needed for? I don't have a clear picture about all the hardware involved yet.

> I am not sure if we are on the same page: these two loops are arbitrary and don't have any relevance. Any module should work together with any other module, there shouldn't be a normal or sensor mode. Sensors should be a normal module like any other.

We're on the same page, this refactor was just to assess how the program works right now. Of course there will only be one event loop with different capabilities, that can be enabled and disabled.

> It is important that we have intermediate steps every day, so that we soon can start testing. Let us first get weather station+sensors running on the new architecture (the file writes done in the sensor loop can be dropped, they are not important).

Good idea. I'll make a PR soon with the first step.

**Comment by markus2330** [comment]
> What is the MOD-IO2 needed for?

Currently only for the "buttons" module.

>  I'll make a PR soon with the first step.

:rocket:

**Comment by markus2330** [comment]
All seems to be done now.
